### ISSUE TITLE
Allow sub-tree injection in configuration framework

### ISSUE THREAD

**Issue by urbim** [kumuluz/kumuluzee#183]
If `__kumuluzee-inject` property is defined, inject all configuration from that sub-tree.

The goal is to support something like this:

**config.yml:**

```yaml
kumuluzee:
  health:
    checks:
      kafka-health-check:
        __kumuluzee-inject: "kumuluzee.streaming.producer"
        a: 2 # override
        c: 3 # define new

  streaming:
    producer:
      a: 1 # gets overridden
      b: test # defines new
      d:
        e: nested # defines nested
```

This would create effective configuration:

```yaml
kumuluzee:
  health:
    checks:
      kafka-health-check:
        a: 2
        b: test
        c: 3
        d:
          e: nested

  streaming:
    producer:
      a: 1
      b: test
      d:
        e: nested
```

This allows developers to write repeatable configuration only once (DRY) while still allowing overrides to be defined.
