### ISSUE TITLE
ConfigurationUtil.get(String) returning String representation instead of Optional.empty()

### ISSUE THREAD

**Issue by osbeorn** [kumuluz/kumuluzee#215]
Assume we have the following config.yml

```yaml
mp:
  jwt:
    verify:
      publickey:
        location: http://localhost:8081/jwks
      issuer: http://example.com

```

We then try to get the `mp.jwt.verify.publickey` property like so
```
Optional<String> value = ConfigurationUtil.getInstance().get("mp.jwt.verify.publickey");
```

The resulting value is
```
{location=https:localhost:8081/jwks}
```
which is a string representation of the leftover leaf in the YAML structure.

The expected result is actually `Optional.empty()`.
